const QUERY_KEY_POINT_OF_INTEREST_LIST = "pointOfInterestList";
const QUERY_KEY_POINT_OF_INTEREST_DETAILS = "pointOfInteresDetails";

export {
  QUERY_KEY_POINT_OF_INTEREST_LIST,
  QUERY_KEY_POINT_OF_INTEREST_DETAILS,
};
