const CLOSE_TO_START_DISTANCE = 64;
const CLOSE_TO_START_THRESHOLD = 128;
const FIT_EDGE_PADDING = { top: 24, left: 32, bottom: 24, right: 32 };

export { CLOSE_TO_START_DISTANCE, CLOSE_TO_START_THRESHOLD, FIT_EDGE_PADDING };
